rethinkdb:
  image: rethinkdb
  ports:
    - "8080:8080" # rethinkdb
    - "28015:28015"
    - "29015:29015"

webapp:
  build: .
  working_dir: /src
  volumes:
    - ./:/src
  links:
    - rethinkdb
  ports:
    - "3000:3000" # api/express server
    - "3001:3001"
  env_file: .env
  env_file:
    - ./variables.env
  command: npm start
